(defun get-byte-test ()
  "Тестирование чтения байт"
  (print "get-byte-test")
  (set-bin-src #(255 132 122))
  (print (assert (get-byte) 255))
  (print (assert (get-byte) 132))
  (print (assert (get-byte) 122)))

(defun get-word-test ()
  "Тестирование чтения слова"
  (print "get-word-test")
  (set-bin-src #(0x10 0xff 0xcc 0xcb))
  (print (assert (get-word) 0x10ff))
  (set-little-endian)
  (print (assert (get-word) 0xcbcc)))

(defun get-4bit-test ()
  "Тестирование чтения четырех бит"
  (print "get-4bit-test")
  (set-bin-src #(0x67))
  (print (assert (get-4bit) '(6 . 7))))

(defun get-bit-be-test ()
  "Тестирование чтения бита (big endian)"
  (print "get-bit-be-test")
  (set-bin-src #(5 0xb1))
  (set-big-endian)
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 1)))

(defun get-bit-le-test ()
  "Тестирование чтения бита (little endian)"
  (print "get-bit-le-test")
  (set-bin-src #(0x6f))
  (set-little-endian)
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 0))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 1))
  (print (assert (get-bit) 0)))

(defun get-array-test ()
  "Тестирование чтения массива"
  (print "get-array-test")
  (set-bin-src #(0x16 0xff 0xa0))
  (print (assert (get-array 2) #(22 255)))
  (print (assert (get-array 1) #(160))))

(defun get-struct-test ()
  "Тестирование чтения структуры"
  (print "get-struct-test")
  (set-bin-src #(10 1 0 2 0 0x23 1 2 3))
  (set-big-endian)
  (setq temp (get-struct '((accuracy . byte) (height . word) (width . word) (other . bits4) (array . 3))))
  (print (assert (get-hash temp 'accuracy) 10))
  (print (assert (get-hash temp 'height) 256))
  (print (assert (get-hash temp 'width) 512))
  (print (assert (get-hash temp 'other) '(2 . 3)))
  (print (assert (get-hash temp 'array) #(1 2 3))))

(defun get-bits-test ()
  "Тестирование чтения нескольких бит 10110100"
  (print "get-bits-test")
  (set-bin-src #(180))
  (set-big-endian)
  (print (assert (get-bits 5) 22))
  (print (assert (get-bits 3) 4)))

(get-byte-test)
(get-word-test)
(get-4bit-test)
(get-bit-be-test)
(get-bit-le-test)
(get-array-test)
(get-struct-test)
(get-bits-test)