(set-bin-src #(255 132 122 0x10 0xff 0xcc 0xcb 0x67))
(assert (get-byte) 255)
(assert (get-byte) 132)
(assert (get-byte) 122)
(assert (get-word) 0x10ff)
(set-little-endian)
(assert (get-word) 0xcbcc)
(assert (get-4bit) '(6 . 7))
(set-bin-src #(5 0xb1))
(set-big-endian)
(assert (get-bit) 0)
(assert (get-bit) 0)
(assert (get-bit) 0)
(assert (get-bit) 0)
(assert (get-bit) 0)
(assert (get-bit) 1)
(assert (get-bit) 0)
(assert (get-bit) 1)
(assert (get-bit) 1)
(assert (get-bit) 0)
(assert (get-bit) 1)
(assert (get-bit) 1)
(assert (get-bit) 0)
(assert (get-bit) 0)
(assert (get-bit) 0)
(assert (get-bit) 1)
(set-bin-src #(0x6f))
(set-little-endian)
(assert (get-bit) 1)
(assert (get-bit) 1)
(assert (get-bit) 1)
(assert (get-bit) 1)
(assert (get-bit) 0)
(assert (get-bit) 1)
(assert (get-bit) 1)
(assert (get-bit) 0)
;Тестирование чтения структуры
(set-bin-src #(10 1 0 2 0 0x23 1 2 3))
(set-big-endian)
(setq temp (get-struct '((accuracy . byte) (height . word) (width . word) (other . bits4) (array . 3))))
(assert (get-hash temp 'accuracy) 10)
(assert (get-hash temp 'height) 256)
(assert (get-hash temp 'width) 512)
(assert (get-hash temp 'other) '(2 . 3))
(assert (get-hash temp 'array) #(1 2 3))

