(defun hash-test ()
  (setq a (make-hash))
  (setq b (make-hash))
  (set-hash a 'x 5)
  (set-hash a 'y 10)
  (set-hash a 'x 25)
  (set-hash a 'z 35)
  (set-hash a 't 42)
  (print (assert (get-hash a 't) 42))
  (set-hash a 's 11)
  (set-hash a 'h 55)
  (print (assert (check-key a 'y) t))
  (print (assert (check-key a 'm) nil))
  (remove-key a 'h)
  (print (assert (check-key a 'h) nil)))

(hash-test)
