(setq q (queue-create))
(queue-push q 1)
(queue-push q 2)
(queue-push q 3)
(assert q '(queue 1 2 3))
(queue-push (list 1 2 3) 3)
(let ((a (queue-pop q))
      (b (queue-pop q))
      (c (queue-pop q))
      (d (queue-pop q)))
  (print (assert a 1))
  (print(assert b 2))
  (print(assert c 3))
  (assert d nil))
