(handle
 (progn
   (clear-screen)

   (run-tests 'stop-on-fail)
  )
 (error (message)
	(print "error:" message))
 (path-not-found (message)
	(print "path-not-found:" message))
 (not-directory (message)
	(print "not-directory:" message))
 (not-file (message)
	(print "not-file:" message))
 (read-only (message)
	(print "read-only:" message))
 (not-enough-space (message)
	(print "not-enough-space:" message))
 (end-of-file (message)
	(print "end-of-file:" message))
 (not-empty-dir (message)
	(print "not-empty-dir:" message))
 (argument-error (message)
	(print "argument-error:" message))
 )
