(svga-init 0 2)
(print "SVGA bases:")
(print *svga-io-base*)
(print *svga-fb-base*)
(print *svga-fifo-base*)
(print "Id: " (svga-read-reg 0))
(print "Enable: " (svga-read-reg +svga-reg-enable+))
(print "Width: " (svga-read-reg 2))
(print "Height: " (svga-read-reg 3))
(print "Max Width: " (svga-read-reg 4))
(print "Max Height: " (svga-read-reg 5))
(print "Depth: " (svga-read-reg 6))
(print "Pitch: " *svga-pitch*)
(print "VRAM size: " *svga-vram-size*)
(print "FB size: " *svga-fb-size*)
(print "FIFO size: " *svga-fifo-size*)
(print "Caps: " (svga-read-reg 17))
(print "Fifo start: " (svga-read-reg 18))
(print "Sync: " (svga-read-reg 21))
(print "Config done: " (svga-read-reg +svga-reg-config-done+))
(let* ((width 640)
       (height 480)
       (size (* width 4))
       (a (make-array size))
       (pos *svga-fb-base*)
       (row 0))
  (svga-set-mode width height 32)
  (let ((s (new-stream)))
    (write-dword s 0xff00ff)
    (for y 0 height
  	 (setq row pos)
  	 (setq pos (+ pos size))
  	 ;; (for x 0 width
  	 ;;      (memcpy row (ostream-data s))
  	 ;;      (setq row (+ row 4))
  	 ;;      (svga-update x y 1 1)))))
  	 (for x 0 width
	      (seta a (<< x 2) (% x width))
	      (seta a (+ 1 (<< x 2)) (% y height))
	      (seta a (+ 2 (<< x 2)) 0xff)
	      (seta a (+ 3 (<< x 2)) 0xff))
	 (memcpy row a)
	 (svga-update 0 y width 1))))
