(svga-init 0 2)
(print "SVGA bases:")
(print *svga-io-base*)
(print *svga-fb-base*)
(print *svga-fifo-base*)
(print "Id: " (svga-read-reg 0))
(print "Enable: " (svga-read-reg +svga-reg-enable+))
(print "Width: " (svga-read-reg 2))
(print "Height: " (svga-read-reg 3))
(print "Max Width: " (svga-read-reg 4))
(print "Max Height: " (svga-read-reg 5))
(print "Depth: " (svga-read-reg 6))

(print "VRAM size: " *svga-vram-size*)
(print "FB size: " *svga-fb-size*)
(print "FIFO size: " *svga-fifo-size*)
(print "Caps: " (svga-read-reg 17))
(print "Config done: " (svga-read-reg +svga-reg-config-done+))
(svga-set-mode 640 480 32)
(let ((a (make-array (* 320 200 4))))
  (for i 0 1024
       (seta a i 0xff))
  (memcpy *svga-fb-base* a))
