#!/bin/bash
SOURCE=$(printf '%s' "$(cat /tmp/compile)")
ESC=$(echo "${SOURCE}" | sed -e 's/[&"*+^/\\]/\\&/g' -e 's/$/\\/'; echo " ")
#echo "s/\*TARGET\*/$ESC/" >/tmp/1
cat bin/compiler | sed -e "s/\*TARGET\*/$ESC/" >/tmp/bin
