var menudata={children:[
{text:"Титульная страница",url:"index.html"},
{text:"Классы",url:"annotated.html",children:[
{text:"Классы",url:"annotated.html"},
{text:"Алфавитный указатель классов",url:"classes.html"},
{text:"Члены классов",url:"functions.html",children:[
{text:"Указатель",url:"functions.html"},
{text:"Переменные",url:"functions_vars.html"}]}]},
{text:"Файлы",url:"files.html",children:[
{text:"Файлы",url:"files.html"},
{text:"Список членов всех файлов",url:"globals.html",children:[
{text:"Указатель",url:"globals.html",children:[
{text:"a",url:"globals.html#index_a"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"g",url:"globals.html#index_g"},
{text:"i",url:"globals.html#index_i"},
{text:"k",url:"globals.html#index_k"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"p",url:"globals.html#index_p"},
{text:"r",url:"globals.html#index_r"},
{text:"s",url:"globals.html#index_s"},
{text:"t",url:"globals.html#index_t"},
{text:"u",url:"globals.html#index_u"},
{text:"v",url:"globals.html#index_v"},
{text:"w",url:"globals.html#index_w"}]},
{text:"Функции",url:"globals_func.html",children:[
{text:"a",url:"globals_func.html#index_a"},
{text:"c",url:"globals_func.html#index_c"},
{text:"d",url:"globals_func.html#index_d"},
{text:"e",url:"globals_func.html#index_e"},
{text:"g",url:"globals_func.html#index_g"},
{text:"i",url:"globals_func.html#index_i"},
{text:"k",url:"globals_func.html#index_k"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"p",url:"globals_func.html#index_p"},
{text:"r",url:"globals_func.html#index_r"},
{text:"s",url:"globals_func.html#index_s"},
{text:"t",url:"globals_func.html#index_t"},
{text:"w",url:"globals_func.html#index_w"}]},
{text:"Переменные",url:"globals_vars.html"},
{text:"Определения типов",url:"globals_type.html"},
{text:"Макросы",url:"globals_defs.html"}]}]}]}
