echo "---------------test_pair---------------"
sh sys_test "(RPLACA '(a b c) 1)" "(1 B C)"
sh sys_test "(RPLACA)" "RPLACA: no params"
sh sys_test "(RPLACA '(a b c))" "RPLACA: not enough params"
sh sys_test "(RPLACA '(a b c) 1 3)" "RPLACA: too many params"
sh sys_test "(RPLACA 2 1)" "RPLACA: first param is not pair"
sh sys_test "(RPLACA '(a b c) NIL)" "(NIL B C)"
sh sys_test "(RPLACA NIL 2)" "RPLACA: empty list"
sh sys_test "(RPLACD '(a b c) 2)" "(A . 2)"
sh sys_test "(RPLACD '(a b c) NIL)" "(A)"
sh sys_test "(RPLACD)" "RPLACD: no params"
sh sys_test "(RPLACD '(a b c))" "RPLACD: not enough params"
sh sys_test "(RPLACD '(a b c) 1 3)" "RPLACD: too many params"
sh sys_test "(RPLACD 2 1)" "RPLACD: first param is not pair"
sh sys_test "(RPLACD '(a b c) '(d e))" "(A D E)"
sh sys_test "(RPLACD '(NIL b c) '(d e))" "(NIL D E)"
sh sys_test "(RPLACD NIL 2)" "RPLACD: empty list"
