echo "---------------test_pair---------------"
sh sys_test "(RPLACA '(a b c) 1)" "(1 B C)"
sh sys_test "(RPLACA)" "RPLACA: invalid arguments count"
sh sys_test "(RPLACA '(a b c))" "RPLACA: invalid arguments count"
sh sys_test "(RPLACA '(a b c) 1 3)" "RPLACA: invalid arguments count"
sh sys_test "(RPLACA 2 1)" "RPLACA: first param is not list"
sh sys_test "(RPLACA '(a b c) NIL)" "(() B C)"
sh sys_test "(RPLACA NIL 2)" "RPLACA: list is empty"
sh sys_test "(RPLACD '(a b c) 2)" "(A . 2)"
sh sys_test "(RPLACD '(a b c) NIL)" "(A)"
sh sys_test "(RPLACD)" "RPLACD: invalid arguments count"
sh sys_test "(RPLACD '(a b c))" "RPLACD: invalid arguments count"
sh sys_test "(RPLACD '(a b c) 1 3)" "RPLACD: invalid arguments count"
sh sys_test "(RPLACD 2 1)" "RPLACD: first param is not list"
sh sys_test "(RPLACD '(a b c) '(d e))" "(A D E)"
sh sys_test "(RPLACD '(NIL b c) '(d e))" "(NIL D E)"
sh sys_test "(RPLACD NIL 2)" "RPLACD: list is empty"
