
(clear-screen)
;; (let (;; (el (make-element 0 10 1 30 14 +white+ +red+ 0 0 0))
;;       ;; (el2 (make-element 0 5 15 30 5 +red+ +red+ 0 0 0))
;;       ;; (el3 (make-element 0 60 12 13 5 +yellow+ +blue+ 0 0 0))
;;       ;; (text1 (make-text 0 70 3 5 10 NIL NIL NIL NIL NIl "Hello world" +red+))
;;       ;; (text2 (make-text 0 60 20 10 10 NIL NIL NIL NIL NIl "Hello world again" +white+))
;;       ;; (text3 (make-text 0 60 7 7 10 NIL NIL NIL NIL NIl "when  rem is 0 test12" +white+))
;;       ;; (text4 (make-text 0 40 5 10 10 +green+ NIL NIL NIL NIl "Green background" +white+))
;;       ;; (block1 (make-block 0 10 10 10 10 +white+ NIL NIL NIL NIL '()))
;;       ;; (el1block1 (make-element 0 0 0 2 2 +red+ 0 0 0 0))
;;       ;; (text1block1 (make-text 0 2 2 5 5 +green+ 0 0 0 0 "in box" +blue+))
;;       ;; (el1vert1 (make-element 0 0 0 2 2 +red+ 0 0 0 0))
;;       ;; (el2vert1 (make-instance element))
;;       ;; (text1vert1 (make-text 0 0 0 5 5 +red+ 0 0 0 0 "in vert" +blue+))
;;       ;; (vert1 (make-vert 0 10 10 22 1 +white+ 0 0 0 0 '() 2 0 T))
;;       ;; (el1horiz1 (make-element 0 0 0 2 2 +red+ 0 0 0 0))
;;       ;; (el2horiz1 (make-element 0 0 0 2 2 +green+ 0 0 0 0))
;;       ;; (text1horiz1 (make-instance text))
;;       ;; (horiz1 (make-horiz 0 1 1 22 1 +white+ 0 0 0 0 '() 2 0 T))
;;       (e1 (element (x 10) (y 10) (width 10) (height 10)))
;;       (b1 (block (x 2) (y 2) (width 10) (height 10)
;; 		 (vert (x 4) (y 4) (width 10) (height 10) (back-colour +white+)
;; 		        (text (x 2) (y 2) (text "123") (width 4) (height 4) (back-colour +red+))
;; 		        (element (x 4) (y 4) (width 2) (height 2) (back-colour +green+)))))
;;       )
;;   ;(add-child block1 el1block1)
;;   ;(add-child block1 text1block1)
;;   ;;(draw block1)
;;   ;; (set-defaults el2vert1)
;;   ;; (set-defaults text1horiz1)
;;   ;; (add-child vert1 el1vert1)
;;   ;; (add-child vert1 el2vert1)
;;   ;; (add-child vert1 text1vert1)
;;   ;; (draw vert1)
;;   ;; (add-child horiz1 el1horiz1)
;;   ;; (add-child horiz1 el2horiz1)
;;   ;; (add-child horiz1 text1horiz1)
;;   ;; (draw horiz1)
;;   (draw b1)
;;   ;(draw e1)
;;   ;; (setq *key-down-handler* #'(lambda (key) (element-set-x el1horiz1 (++ (element-x el1horiz1)))
;;   ;; 			       (draw horiz1)
;;   ;; 			       (draw-screen)))
;;   ;(draw el)
;;   ;(draw el2)
;;   ;(draw el3)
;;   ;(draw text1)
;;   ;(draw text2)
;;   ;(draw text3)
;;   ;(draw text4)
;;   ;(move-to 10 10)
;;   )
(set-screen
 ;; (block (x 2) (y 2) (width 10) (height 10) (active-colour +green+)
 ;; 	(vert (x 4) (y 4) (width 10) (height 9) (back-colour +white+) (active-colour +green+)
	      (text (x 2) (y 2) (text "123") (width 4) (height 3) (back-colour +red+) (active-colour +green+))
	      (element (x 4) (y 4) (width 2) (height 2) (active-colour +green+))
	      (text (x 5) (y 5) (text "111111111111111111"))
	      (text (x 5) (y 6) (text "222222222222222222")))
;; (print 1 *draw-top-left* *draw-bottom-right*)
;; (draw *gui-screen*)
;; (print 2 *draw-top-left* *draw-bottom-right*)
;; (draw *gui-screen*)
;; (print 3 *draw-top-left* *draw-bottom-right*)
;; (draw *gui-screen*)
;; (print 4 *draw-top-left* *draw-bottom-right*)
;; (draw *gui-screen*)
;; (print 5 *draw-top-left* *draw-bottom-right*)
;; (draw *gui-screen*)
;; (print 6 *draw-top-left* *draw-bottom-right*)
;; (draw *gui-screen*)
