(clear-screen)

(set-screen
 (block (x 2) (y 2) (width 10) (height 10) (active-colour +green+)
	(horiz (width 1) (height 1) (id 2) (keydown #'(lambda (k)
							(add-child (get-element-by-id 2)
								   (block (width 3) (height 2)))
							(update-screen))))
	(vert (id 1) (x 4) (y 4) (width 10) (height 9) (back-colour +white+) (active-colour +green+)
	      (text (x 2) (y 2) (text "123") (width 4) (height 3) (back-colour +red+) (active-colour +green+))
	      (element (x 4) (y 4) (width 2) (height 2) (active-colour +green+))
	      (text (x 5) (y 5) (text "111111111111111111") (keydown #'(lambda (k) (set-screen (element)))))
	      (text (x 5) (y 6) (text "222222222222222222")
		    (keydown #'(lambda (k) (add-child (get-element-by-id 1) (element (height 1) (width 1)))
				 (update-screen)))))))
