(defvar +player-im+ (make-image `#(#(0 111 0)
				   #(47 124 92)
				   #(47 0 92))))
(defvar +wall-im+ (make-image `#(#(35 35 35)
				 #(35 35 35))))
(defvar +floor-im+ (make-image `#(#(61 61 61)
				  #(0 0 0))))
(defvar +ceiling-im+ (make-image `#(#(0 0 0)
				    #(95 95 95))))
(defvar +spike-im+ (make-image `#(#(0 94 0)
				  #(47 0 92))))
(defvar +empty-im+ (make-image `#(#(0 0 0)
				  #(0 0 0))))

(defvar *tiles-atlas* `((RWALL . ,+wall-im+)
			(LWALL . ,+wall-im+)
			(FLOOR . ,+floor-im+)
			(CEILING . ,+ceiling-im+)
			(SPIKE . ,+spike-im+)
			(nil . ,+empty-im+)))

(defvar *level* `#(#(LWALL CEILING CEILING CEILING CEILING CEILING CEILING CEILING CEILING CEILING CEILING RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		 ; Дальше идет какая-то коллизия при попытке отрисовки в буфере
		 ; #(LWALL nil nil RWALL)
		 ; #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		 ; #(LWALL nil nil nil nil nil nil nil nil nil nil RWALL)
		   #(LWALL FLOOR FLOOR FLOOR FLOOR FLOOR FLOOR FLOOR FLOOR FLOOR FLOOR RWALL)))

(defun update-game ()
  "Выполняет обновление состояния игры"
  (plat-update)
  (draw-screen))

(setq *screen-height* 50)
(set-colour +light-gray+)
(set-tile-size (make-vec2 3 2))
(set-tiles *tiles-atlas*)
(plat-set-level *level*)

(defvar +player-spr+ (new-sprite +player-im+ (make-vec2 0 0) 0))
(defvar +player+ (new-entity (make-vec2 5 5) +player-spr+))
(update-game)
;(mob-set-pos (entity-mob +player+) (make-vec2 1 3))
;(update-game)
