object_t add(object_t list);
object_t add2(object_t list);
object_t sub(object_t first, object_t list);
object_t sub2(object_t first, object_t list);
object_t mul(object_t list);
object_t mul2(object_t list);
object_t DIV(object_t first, object_t list);
object_t DIV2(object_t first, object_t list);
object_t mod(object_t first, object_t list);
object_t bitwise_and(object_t list);
object_t bitwise_or(object_t list);
object_t bitwise_xor(object_t list);
object_t shift_left(object_t obj1, object_t obj2);
object_t shift_right(object_t obj1, object_t obj2);
object_t bitwise_not(object_t list);
object_t less(object_t obj1, object_t obj2);
object_t gt(object_t obj1, object_t obj2);
object_t equal(object_t obj1, object_t obj2);
object_t SIN(object_t obj1);
object_t COS(object_t obj1);
object_t SQRT(object_t obj1);
object_t ROUND(object_t obj1);
void init_arith();
